### ISSUE TITLE
Expand README to assist taskwarrior users unfamiliar with ansible

### ISSUE THREAD

**Issue by linuxcaffe** [kulla/ansible-role-taskwarrior#4]
I'm just learning about ansible roles, and it looks like pure Redhat genius! Problem is that after installing ansible, I havent yet figured out how to run this (or any other) role/ playbook. Maybe please just this once, a paragraph explaining how a simple task user might use this (or any other) role. Thanks!

**Comment by kulla** [comment]
You can have a look at my ansible scripts at https://github.com/kulla/my-ansible-scripts how I use it. The configurations lay at https://github.com/kulla/my-ansible-scripts/blob/master/host_vars/main_computer/variables.yml#L50-L57 and at https://github.com/kulla/my-ansible-scripts/blob/master/main_computer.yml#L7 I have included the rule. See https://github.com/kulla/my-ansible-scripts/blob/master/run.sh for how I run the ansible script.

However I do not know how to apply a role directly from the command line. However I am sure the community can help you. There are [https://www.ansible.com/community](IRC channels) and I am sure StackOverflow will work as well...
