### ISSUE TITLE
Update/ test this role against latest taskwarrior

### ISSUE THREAD

**Issue by linuxcaffe** [kulla/ansible-role-taskwarrior#5]
It's been a while since this role hit the Galaxy, could you try running it on the latest development branch version? A fairly major release is anticipated and it might be great to have a role ready for it. Thanks!

**Comment by kulla** [comment]
This role installs taskwarrior from the local package manager (e.g. apt on debian / ubuntu) and does not compile it from source, see https://github.com/kulla/ansible-role-taskwarrior/blob/master/tasks/main.yml#L5 Thus this role works when the new version of taskwarrior is added to the package manager of your distribution... When you want to use the most up to date version of taskwarrior you need to use another role or you need to write the necessary tasks by yourself.
